### ISSUE TITLE
/biome command is broken

### ISSUE THREAD

**Issue by mathias-github** [mc-server/Essentials#39] opened 2015-07-24 20:51 UTC
This error appears in the console:
[16:50:13] LUA: Plugins/Essentials/general.lua:5: attempt to concatenate global 'biome' (a nil value)
[16:50:13] Stack trace:
[16:50:13]   Plugins/Essentials/general.lua(5): (no name)
[16:50:13] Stack trace end
[16:50:13] Error in plugin Essentials calling function <callback>()

**Comment by mathias-github** [comment] 2015-09-07 16:32
The issue seems to be fixed.

**Comment by tonibm19** [comment] 2015-09-08 07:57
closing then.
No idea about the cause

**Closed by tonibm19** 2015-09-08 07:57 UTC
